version: '3.4'

services:
  api:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5050:5050

  frontend:
    image: frontend
    build:
      context: Frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]


#db da rivedere tutto 
  db:
    image: versione mysql
    networks:
      - api
      environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
      container_name: 