version: '3.4'

services:
  api:
    image: progettoppm12
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5050"]
    ports:
      - 5050:5050
      - 5678:5678
    environment:
      - FLASK_APP=Backend\app.py
      
  frontend:
    image: frontend
    build:
      context: Frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
