version: '3.9'

services:

  frontend:
    container_name: frontend
    image:  frontend
    build: 
      context: frontend
    depends_on:
      - api
    ports:
      - 5050:5050
    networks:
      - database

  api:
    container_name: backend
    image: backend
    build:
      context: .
    depends_on:
      - db  
    ports:
      - 5000:5000
    volumes:
      - ./:/src
    links:
      - db
    environment:
      DB_HOST: db
      DB_USER: pose
      DB_PORT: 3305
      DB_PASSWORD: pose
      DB_NAME: pose
    networks:
      - database  

  db:
    image: mysql:8.0.30
    cap_add:
      - SYS_NICE
      - MAC_ADMIN
      - AUDIT_CONTROL
      - AUDIT_READ
      - BLOCK_SUSPEND
      - BPF
      - CHECKPOINT_RESTORE
      - DAC_READ_SEARCH
      - IPC_LOCK
      - IPC_OWNER
      - LEASE
      - LINUX_IMMUTABLE
      - MAC_OVERRIDE
      - NET_ADMIN
      - NET_BROADCAST
      - PERFMON
      - SYS_ADMIN
      - SYS_BOOT
      - SYS_MODULE
      - SYS_PACCT
      - SYS_PTRACE
      - SYS_RAWIO
      - SYS_RESOURCE
      - SYS_TIME
      - SYS_TTY_CONFIG
      - SYSLOG
      - WAKE_ALARM
    restart: always
    ports:
      - 3305:3305
    environment:
       MYSQL_DATABASE: pose
       MYSQL_PASSWORD: pose
       MYSQL_USER: pose
       MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql/init.sql:/docker-entrypoint-initdb.d/init.sql  
    networks:
      - database

networks:
  database:

volumes:
  db:
    driver: local      
