version: '3.5'

services:
  api:
    container_name: backend
    image: backend
    build:
      context: .
    depends_on:
      - db  
    ports:
      - 5000:5000
    volumes:
      - ./:/src
    links:
      - db
    environment:
      DB_HOST: db
      DB_USER: pose
      DB_PORT: 3305
      DB_PASSWORD: pose
      DB_NAME: pose

  db:
    image: mysql:8.0.30
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - 3305:3306
    environment:
       MYSQL_DATABASE: pose
       MYSQL_PASSWORD: pose
       MYSQL_USER: pose
       MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  
    networks:
      - database

networks:
  database:

volumes:
  db:
    driver: local      
