version: '3.4'

services:
  api:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 5000:5000
    secrets:
      - db-password
    volumes:
      - ./backend/src:/code/src:ro
      - ./backend/package.json:/code/package.json
      - ./backend/package-lock.json:/code/package-lock.json
    depends_on:
      - db

  frontend:
    image: frontend
    build:
      context: Frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5050:5050
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
    depends_on:
      - api

  db:
    image: mysql:8.0.30
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      - MYSQL_ROOT_PASSWORD=pose_apppsw
      - MYSQL_DATABASE=pose_app
      - MYSQL_USER=pose_app
      - MYSQL_PASSWORD=pose_apppsw
    expose:
      - 3306
<<<<<<< HEAD

  
=======
>>>>>>> b3f8dec73262a57d573c2b5d14529f93ca8314f6
