version: '3.4'

services:
  api:
    container_name: backend
    image: backend
    build:
      context: .
    depends_on:
      - db  
    ports:
      - 5000:5000
    volumes:
      - ./:/src
    links:
      - db
    environment:
      DB_HOST: db
      DB_USER: flask
      DB_PASSWORD: pose_apppsw
      DB_NAME: pose_appdocker

  db:
    image: mysql:8.0.30
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - 3305:3305
    environment:
       MYSQL_DATABASE: pose_appdocker
       MYSQL_PASSWORD: secret
       MYSQL_USER: flask
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  
    networks:
      - database

networks:
  database:

volumes:
  db:
    driver: local      
